@startuml
Collection -> Manifest

note  top of Collection : "a way to put links to \nmanifests for cultural heritage objects\nin a particular collection"
note "The basic cultural heritage object part.\nEvery cultural heritage object starts with this" as N2
note "A group of things that are part of\nthe cultural heritage object. A sequence contains\nat least one Canvas" as N3
note "The envelope for a a thing that needs\nto be displayed as part of a sequence\nthat may or may not have extra information\nthat needs to be transmitted to the user\nalong with the thing." as N4
note "A list 1 or more Annotations or Resources" as N5
note "The descriptive wrapper for a ressource.\nIt's where optional descriptive metadata\nabout a particular resource can be put" as N6
note "The leaf node of the tree which ends\nwith a resource which can be resolved\nand displayed on the user's screen" as N7

Manifest -> Sequence
Manifest .. N2
Sequence .. N3
Sequence -> Canvas
Canvas -> Image

Canvas .. N4

Image -> Annotation
Image -> Resource

Image .. N5
Annotation .. N6
Annotation -> Resource
Resource .. N7


@enduml